#!/bin/bash

if [ "$OSX" ] ; then
  alias g="mvim"
  alias ls="gls --color=auto"
  alias clobber="rake db:drop:all db:create:all db:migrate db:test:prepare && say -v Zarvox 'boom goes the dynamite'"
  alias gitx='gitx --all'
  alias hammer="clobber"
  alias clobbah="clobber"
  alias pewpew="git reset --hard HEAD && git clean -f && say -v princess 'pew pew pew'"
  alias ANNOYMODE="export ANNOY_MODE=1"
  alias SHUTUP="unset ANNOY_MODE"
  alias sweep="rm ~/tmp/*.swp"

  alias find="gfind"
  alias locate="glocate"
  alias updatedb="gupdatedb"
  alias oldfind="goldfind"
  alias xargs="gxargs"

  alias clb='cl ; bundle '
  alias clr='clb exec rake'
  alias clc='clb exec pry'
fi

if [ "$LINUX" ] ; then
  alias ls="ls --color=auto"
fi

if dirstack --version &>/dev/null ; then
  alias push="dirstack push"
  alias pop="dirstack pop"
  alias ds="dirstack"
  alias jump="dirstack jump"
  alias jt="dirstack jump"
  alias switch='dirstack jump && dirstack swap'
fi

#common stuff
alias cd..='cd ..'

#alias to reload aliases... meta...
if [ "$OSX" ] ; then
  alias reload='source ~/.profile'
elif [ "$LINUX" ] ; then
  alias reload='source ~/.bash_profile'
fi

alias edit-aliases="vim $HOME/.bash/aliases && reload"
alias edit-functions="vim $HOME/.bash/functions && reload"

alias gru='git remote update -p'
alias grom='git rebase origin/master'

#save me a character, please.
alias vi=vim

alias psf="ps aux | grep"

alias mdr=maildir
alias pictures="railroady -b -M > doc/models.dot ; dot -Tsvg doc/models.dot > doc/models.svg ; open doc/models.svg"

alias wip='git add . ; git ci -a -m "wip"'
alias unwip='git reset HEAD^'
alias reset!='git reset --hard HEAD'

alias heroku_keyswap="ssh-add -D ; ssh-add ~/.ssh/heroku"

alias exterminate="sudo kill -9"


